mappings:
  MEMORY_1:
    MACRO_1:
      name: example-A
      string: A
      type: key
      value: [1, 30]
    MACRO_2:
      name: example-cut
      string:
      - [Ctrl, X]
      - [Ctrl, V]
      type: macro
      value:
      - - [1, 29]
        - [1, 45]
      - - [1, 29]
        - [1, 47]
    MACRO_3:
      name: example-nice
      string:
      - [N]
      - [I]
      - [C]
      - [E]
      type: macro
      value:
      - - [1, 49]
      - - [1, 23]
      - - [1, 46]
      - - [1, 18]
settings: {usbTimeout: 1000}
